### ISSUE TITLE
Any interest in an OPTIMADE querier?

### ISSUE THREAD

**Issue by ml-evs** [pedrobcst/Xerus#2]
Hi there, very interesting package!

I am just wondering if you would be interested in implementing an [OPTIMADE API](https://optimade.org) querier class, which would provide unified access to all crystal structure databases in the [OPTIMADE consortium](https://www.optimade.org/providers-dashboard/). I would be interested in helping with the implementation!

**Comment by pedrobcst** [comment]
Hey Evan, thank your for the comment!

Actually I have looked before into OPTIMADE API and I was planning in the upcoming future to try to include it, since it provides a unified access to all crystal structures databases. Honestly speaking, the current queriers are all over the place with different implementations and this might be a good opportunity to rewrite it. Ideally, if everything works well, we can just phase off all the other providers implementation and move everything to OPTIMADE.

**Comment by ml-evs** [comment]
Great! I am happy to write a first draft if you like, given that I know the details of the specification already? 

We are planning on writing a client within the [optimade-python-tools](https://github.com/Materials-Consortia/optimade-python-tools) package, and this would help me target that eventual implementation based on a particular use case.

> we can just phase off all the other providers implementation and move everything to OPTIMADE.

Given that you already have implementations for other APIs, I wouldn't recommend deprecating them immediately, as each database tends to provide additional features within their own API compared to OPTIMADE (and sometimes the OPTIMADE API implementations are not quite as well-supported/optimised for each database).

As a side note, I think we would be very interested in deploying Xerus alongside an experimental data management project I am involved with, so you may get some other issues from me as I start to play around with this :)

**Comment by ml-evs** [comment]
> I think if you understand what needs to be done you can go ahead. I am sorry that the codebase is a bit messy, there is alot of refactoring to do.

I can empathise! Nothing to apologise for 🙃 


> The way the queriers works roughly is like this:
> 
>     * Each provider has their own folder where the CIFs are saved
> 
>     * The files are saved in a format of ChemicalFormula_Provider_ProviderID.cif
> 
>     * Usually each querier will take a list of elements and download the whole chemical space (ie, ['Ho', 'B'] -> ['Ho', 'B', 'Ho-B' (HoB2,HoB4,HoB6 etc..)
>
> 
> And then 'multiquery' finishes everything by using each querier independetly:
> 
>     * After this they will be pushed to a 'dump_folder', where later a script will ran to 'test' them and parse their data with pymatgen
> 
>     * After test is finished its pushed into Mongo
> 
> Sadly, when I implemented this I was not thinking ahead of the possibility of adding new providers so its a bit painful. I am up to ideas to clean up this process.

Sound sensible to just slot OPTIMADE in as a new provider (that will itself query multiple databases), and then you can decide how you want to use it.


> I would gladly help you out because I am also interested in learning how to use the OPTIMADE API.

Great, I'll throw together a draft and let you handle the details!

> One question is, how do we deal with overlapping databases? Since there might be an overlap between the current ones and the ones provided by OPTIMADE, how do we decide which API to use?

Well, for one, this would be a nice test for OPTIMADE to see how well the custom APIs match up to the OPTIMADE API implementations (in terms of speed and availability of structures), so I guess we can do some benchmarking to decide. There are already overlaps between e.g. OQMD and Materials Project, presumably at the moment you do not try to match structures across databases? pymatgen does have some tools to do this already.

> If you want to discuss further more ideas, we can talk via some web meeting or something. I am happy also to hear that you are planning to use for a experimental data management. My hope was that this project could help other people, and they would bring ideas on how to improve it (and make it faster, now this 'testing' of CIFs is actually causing a bottleneck), and I would be glad to help anything related to it :)!

Sure thing! Maybe this would be useful a few weeks down the line? We are only just thinking of adding the concept of a crystal structure in our system right now (currently it is targeted at with electrochemistry data but we will be adding some characterization methods too). I guess the idea would be that we have a series of XRD patterns and approximate chemical formulae and this package could help provide some suggestions for assignments (tbh even just a list of the known crystal structures in a particular region of chemical space would be useful, but the XRD aspect brings a lot more value than just automatically running an OPTIMADE query).

**Comment by ml-evs** [comment]
Also, re: #3, in the latest pymatgen versions there is an OPTIMADE client built-in, could be another option as you already have pymatgen as a dep. https://pymatgen.org/pymatgen.ext.optimade.html

I chose to use the optimade-python-tools package as it already has an OPTIMADE -> cif mapping, but maybe if you already have pymatgen -> CIF then just using pymatgen directly could be a better option.

**Comment by pedrobcst** [comment]
> Also, re: https://github.com/pedrobcst/Xerus/issues/3, in the latest pymatgen versions there is an OPTIMADE client built-in, could be another option as you already have pymatgen as a dep. https://pymatgen.org/pymatgen.ext.optimade.html

Actually I am using an older version of pymatgen, I still have to move the codebase to the newest version (I guess that is just changing imports, but I have to check it well)

I started to have a look in Optimade and I think there is few questions, that I think you already raised, but nethertheless:

1. How we use OPTIMADE? As of now, if we just implement with all of the other current API implementations, when we query for example MP/COD in both ways we will end up with similar structures. I saw that your draft actually uses TCOD, and this might be interesting. I usually avoid theoretical structures, but is there any special case we should add?
2. A second point is, if all goes well, we I believe that the OPTIMADE API of OQMD might be better than what I currently have (specially because they serve stability). Specially because their provided API actually does not serve structures (or I could not find in the documentation). What the current Querier does is to get IDs from their API for a given element selection and then scrap the webpage of each ID for the POSCAR of each structure an uses pymatgen to convert from POSCAR to CIF. As you can imagine, if they change their homepage this will easily break.

I will try to get a working implemetation this week. Thanks for all the comments!

**Comment by pedrobcst** [comment]
@ml-evs 
Hi Evan,
Ive been working on the draft you proposed, and there is few things I found out

1. MaterialsProject seems to be the only provider that have a working implementation.
2. It seems that COD/TCOD currently does not support 'HAS ONLY' for example, so I am wondering how can we restrict the structures to certain elements (see https://www.crystallography.net/tcod/optimade/v1/structures?filter=elements%20HAS%20ONLY%20%22Ho%22,%22B%22)
3. OQMD does not provide the full Structural information to generate a CIF using the OPTIMADE Structure adapater. The following error is thrown when trying to parse it:
```python
ValidationError: 2 validation errors for StructureResource
attributes -> elements_ratios
  field required (type=value_error.missing)
attributes -> species
  field required (type=value_error.missing)
```

Any ideas on how to proceed? I will update the PR soon with what I have working for MP..

**Comment by ml-evs** [comment]
> @ml-evs Hi Evan, Ive been working on the draft you proposed, and there is few things I found out
> 
>     1. MaterialsProject seems to be the only provider that have a working implementation.
> 

Most implementations "work", but they may not support all features of the specification. We automatically validate all providers at  https://www.optimade.org/providers-dashboard/ so you can see if there are specific things they do not support.

>     2. It seems that COD/TCOD currently does not support 'HAS ONLY' for example, so I am wondering how can we restrict the structures to certain elements (see https://www.crystallography.net/tcod/optimade/v1/structures?filter=elements%20HAS%20ONLY%20%22Ho%22,%22B%22)

Hmm, annoying (I could maybe ask them if they would implement this optional feature but it depends on the structure of their database/indexes. An equivalent query would be:

[`(elements HAS "Ho" AND elements HAS "B" AND nelements=2) OR (elements HAS "Ho" OR elements HAS "B" AND nelements=1)`](https://www.crystallography.net/cod/optimade/v1/structures?filter=(elements%20HAS%20%22Ho%22%20AND%20elements%20HAS%20%22B%22%20AND%20nelements=2)%20OR%20(elements%20HAS%20%22Ho%22%20OR%20elements%20HAS%20%22B%22%20AND%20nelements=1))

but for larger chemical spaces this becomes a bit long-winded...

>     3. OQMD does not provide the full Structural information to generate a CIF using the OPTIMADE Structure adapater. The following error is thrown when trying to parse it:


> 
> ```python
> ValidationError: 2 validation errors for StructureResource
> attributes -> elements_ratios
>   field required (type=value_error.missing)
> attributes -> species
>   field required (type=value_error.missing)
> ```

Ah yes, another caveat is that each provider can choose which fields to respond with by default. We would need to list all the fields we need to construct a cif file, which I guess here would just be adding `species` to the normal list. Unfortunately the only way to do this is list all the other fields too, something like...

[`&response_fields=species,elements,cartesian_site_positions,lattice_vectors`](http://oqmd.org/optimade/v1/structures?response_fields=species,elements,cartesian_site_positions,lattice_vectors,elements_ratios)

(maybe still some missing, without testing directly).

Another potential problem with the COD is that they do not serve positions through their OPTIMADE API as they are only stored in their CIF files directly. Requesting them makes for very slow queries as they are reconstructed (not sure if they are caching the results as people request them, which might work well here)... As a side point, we are working on a `files` endpoint in the next version of the specification that would allow you to use OPTIMADE for the filtering, and then each database can attach whatever kind of file it wants to each resource, but this might be limiting for the COD for now.

> Any ideas on how to proceed? I will update the PR soon with what I have working for MP..

I can add a commit for the response fields and you can see how it goes.

**Comment by pedrobcst** [comment]
After adding the fields (just needed one more actually!) it worked well for OQMD.
Since COD does not provide the positions, I think we can avoid for now.. Ive added some extra feature to also accept custom provider based filters (like _oqmd_stability). Now just have to think how to integrate it into Xerus and to which use case optimade will be better

**Comment by ml-evs** [comment]
I've actually raised an bug with the COD, if you manually specify a page limit, then the positions can be obtained quite quickly (~ 1 second or so per structure), but if you leave it blank, it uses some large internal page limit that causes timeouts. I've just pushed that fix to my PR too.

**Comment by pedrobcst** [comment]
Hi Evan,
Sorry for the previous mess with PR. It was just easier for me to push the change to my branch and merge. I will add here, a tasklist on what I think needs to be done. Please feel free to adjust

- [ ] Modify the interface to work with COD (Change HAS ONLY to nested ANDs and limit elements?)
- [ ] Investigate on how to smoothly implement OPTIMADE with other queries without overlapping structures (or which provider to use through where)
- [ ] Check if current OQMD and OPTIMADE gives the same structures for a given list of elements. If yes, replace current OQMD hacky implementation with Optimade (straightfoward, does not need to parse HTMLs and convert POSCARs)

**Comment by pedrobcst** [comment]
Hey @ml-evs,
Ive finished the rough implementation of the optimade querier based on your last commit. Now it seems to work correctly when HAS ONLY is not implemented by using HAS ALL with nelements. Ive also tested the consistency between the current queriers (OQMD/COD) with ones via optimade. I will write a small summary below:

### OQMD
OQMD through OPTIMADE works better. The current implementation that I am using is quite 'hacky' since OQMD API does not provide structures directly (Current it goes: Get OQMD Ids -> go to entry page -> parse POSCAR link -> Structure). Actually in this manner, few structures were not being queried correctly.
In this regard, I will deprecate this current implementation in favor of optimade which provides all structures correctly and actually the stability filter works. (This is already the default querier in the optimadev1 branch), and seems to be working fine

### COD
COD is quite tricky. I did few consistency checks and everything works fine unless some extremely heavy data is coming from COD. For example, if you query COD for 'Si-O', there are quite extreme large cifs there (around 1 MB), and it seems that the request dies when trying to get this data (503 error). Currently COD querier retrieve cif urls and just download them directly. 
Querying through OPTIMADE returned 57/322 structures for Si-O. I am wondering if using OPTIMADE might be better still, since all those large cifs usually gives a lot of issues. (I had a structure from COD coming with more than 3k atomic positions, this literally broke GSASII as he could not simulate the pattern for this structure)
So I am wondering what is the best action here, open to suggestions.

### Inconsistency of 'next_url'
This is somethign I noted when testing both COD and OQMD. I do not know if this implementation issue on the provider side, however this is what is currently happening:

* OQMD: OQMD returns the paramater of data['links']['next'] directly as the URL.
* COD: COD returns as a dict, where the next url is inside the 'href' key.

I am wondering what is supposed to be the current implemetantion, and where can I raise an issue regarding this? (I am also supposing that these responses schema are supposed to be same, indepedent of provider)
